name: Desh Raj
description: Personal website
menu:
 - page: Papers
   url: /papers
 - page: Research Projects
   url: /research
 - page: Curriculum Vitae
   url: /assets/DeshRaj.pdf
 - page: ML Blog
   url: "https://medium.com/explorations-in-language-and-learning"

menu_external:
 - title: Google Scholar
   url: "https://scholar.google.co.in/citations?user=Z-7pPYEAAAAJ&hl=en"
 - title: Twitter
   url: "https://twitter.com/raj_desh26"
 - title: LinkedIn
   url: "https://www.linkedin.com/in/rdesh26/"
 - title: GitHub
   url: "https://github.com/desh2608"
 # - title: Medium
 #   url: "https://medium.com/@rdesh26"
mathjax: false
markdown: kramdown
encoding: utf-8
baseurl: /desh2608.github.io
locale: en_GB
theme: jekyll-theme-cayman
repository: desh2608/desh2608.github.io
excerpt_separator: "<!--excerpt-->"
